export VAULT_ADDR="https://10.1.3.121:8200"

HOST_STRING="expernet"
SLD_STRING="cloudtech"
TLD_STRING="team"
DOMAIN_STRING="${SLD_STRING}.${TLD_STRING}"
SUBJECT_CN_STRING="${HOST_STRING}.${DOMAIN_STRING}"
ISSUER_NAME_CN_STRING="expernet cloud tech"

VAULT_ROLE_STRING="common_vault_role"
NO_TLS_STRING="-tls-skip-verify"
KEY_TYPE_STRING="ec"
KEY_BITS_STRING="256"

IP_SAN1_STRING="192.168.60.6"
ALT_NAME1_STRING="${SUBJECT_CN_STRING}"

#IP_SAN2_STRING=""
#ALT_NAME2_STRING=""
TTL_STRING="9528h"
